export const POST_LOADING = 'POST_LOADING';
export const ALL_POKEMONS = 'ALL_POKEMONS';
export const ALL_TYPES = 'ALL_TYPES';
export const RESEARCHED_POKEMON_NAME = 'RESEARCHED_POKEMON_NAME';
export const RESEARCHED_POKEMONS_TYPES = 'RESEARCHED_POKEMON_NAME';
